#!/usr/bin/env python3
# from typing import *

# def solve(N: str, M: str, L: List[str], R: List[str], D: List[str]) -> str:
def solve(N, M, L, R, D):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N, M = input().split()
    L = [None for _ in range(M)]
    R = [None for _ in range(M)]
    D = [None for _ in range(M)]
    for i in range(M):
        L[i], R[i], D[i] = input().split()
    bpv = solve(N, M, L, R, D)
    print(bpv)

if __name__ == '__main__':
    main()
