#!/usr/bin/env python3
# from typing import *

# def solve(N: int, M: int) -> int:
def solve(N, M):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N, M = map(int, input().split())
    kru = solve(N, M)
    print(kru)

if __name__ == '__main__':
    main()
