#!/usr/bin/env python3
# from typing import *

# def solve(N: int, p: List[int]) -> List[str]:
def solve(N, p):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    p = [None for _ in range(N - 1)]
    for i in range(N - 1):
        p[i] = int(next(tokens))
    assert next(tokens, None) is None
    ans = solve(N, p)
    for i in range(N):
        print(ans[i])

if __name__ == '__main__':
    main()
