#!/usr/bin/env python3
# from typing import *

# def solve(A: int, V: int, B: int, W: int, T: int) -> str:
def solve(A, V, B, W, T):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    A, V = map(int, input().split())
    B, W = map(int, input().split())
    T = int(input())
    axc = solve(A, V, B, W, T)
    print(axc)

if __name__ == '__main__':
    main()
