#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N = random.randint(1, 10 ** 9)  # TODO: edit here
    V = [None for _ in range(N)]
    W = [None for _ in range(N)]
    for i in range(N):
        V[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        W[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    Q = random.randint(1, 10 ** 9)  # TODO: edit here
    v = [None for _ in range(Q)]
    L = [None for _ in range(Q)]
    for i in range(Q):
        v[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        L[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(N)
    for i in range(N):
        print(V[i], W[i])
    print(Q)
    for i in range(Q):
        print(v[i], L[i])

if __name__ == "__main__":
    main()
