#!/usr/bin/env python3
# from typing import *

# def solve(N: int, V: List[int], W: List[int], Q: int, v: List[int], L: List[int]) -> Any:
def solve(N, V, W, Q, v, L):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N = int(input())
    V = [None for _ in range(N)]
    W = [None for _ in range(N)]
    for i in range(N):
        V[i], W[i] = map(int, input().split())
    Q = int(input())
    v = [None for _ in range(Q)]
    L = [None for _ in range(Q)]
    for i in range(Q):
        v[i], L[i] = map(int, input().split())
    ans = solve(N, V, W, Q, v, L)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
