#!/usr/bin/env python3
# from typing import *

# def solve(N: str, P: str, S: str) -> int:
def solve(N, P, S):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N, P = input().split()
    S = input()
    mcz = solve(N, P, S)
    print(mcz)

if __name__ == '__main__':
    main()
