#!/usr/bin/env python3
# from typing import *

# def solve(A: int, B: int, C: int) -> int:
def solve(A, B, C):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    A, B, C = map(int, input().split())
    vox = solve(A, B, C)
    print(vox)

if __name__ == '__main__':
    main()
