#!/usr/bin/env python3
# from typing import *

# def solve(N: int, S: List[str], C: List[int]) -> int:
def solve(N, S, C):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    S = [None for _ in range(N)]
    C = [None for _ in range(N)]
    for i in range(N):
        S[i] = next(tokens)
        C[i] = int(next(tokens))
    assert next(tokens, None) is None
    bji = solve(N, S, C)
    print(bji)

if __name__ == '__main__':
    main()
