#!/usr/bin/env python3
# from typing import *

# def solve(A: int, B: int, H: int, M: int) -> float:
def solve(A, B, H, M):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    A, B, H, M = map(int, input().split())
    tau = solve(A, B, H, M)
    print(tau)

if __name__ == '__main__':
    main()
