#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    K = random.randint(1, 10 ** 9)  # TODO: edit here
    a = [None for _ in range(K)]
    for i in range(K):
        a[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(K)
    print(*[a[i] for i in range(K)])

if __name__ == "__main__":
    main()
