#!/usr/bin/env python3
# from typing import *

# def solve(K: int, a: List[int]) -> Any:
def solve(K, a):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    K = int(next(tokens))
    a = [None for _ in range(K)]
    for i in range(K):
        a[i] = int(next(tokens))
    assert next(tokens, None) is None
    ans = solve(K, a)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
