#!/usr/bin/env python3
# from typing import *

# def solve(r: int, g: int, b: int) -> str:
def solve(r, g, b):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    r, g, b = map(int, input().split())
    tfu = solve(r, g, b)
    print(tfu)

if __name__ == '__main__':
    main()
