#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    A = random.randint(1, 10 ** 9)  # TODO: edit here
    B = random.randint(1, 10 ** 9)  # TODO: edit here
    C = random.randint(1, 10 ** 9)  # TODO: edit here
    D = random.randint(1, 10 ** 9)  # TODO: edit here
    print(A, B, C, D)

if __name__ == "__main__":
    main()
