#!/usr/bin/env python3
# from typing import *

# def solve(A: int, B: int, C: int, D: int) -> int:
def solve(A, B, C, D):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    A, B, C, D = map(int, input().split())
    ksy = solve(A, B, C, D)
    print(ksy)

if __name__ == '__main__':
    main()
