#!/usr/bin/env python3
# from typing import *

# def solve(X: int) -> int:
def solve(X):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    X = int(input())
    qwc = solve(X)
    print(qwc)

if __name__ == '__main__':
    main()
