#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.6.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    D = random.randint(1, 10 ** 9)  # TODO: edit here
    T = random.randint(1, 10 ** 9)  # TODO: edit here
    S = random.randint(1, 10 ** 9)  # TODO: edit here
    print(D, T, S)

if __name__ == "__main__":
    main()
