#!/usr/bin/env python3
# from typing import *

# def solve(N: int, A: int, B: int) -> int:
def solve(N, A, B):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N, A, B = map(int, input().split())
    knn = solve(N, A, B)
    print(knn)

if __name__ == '__main__':
    main()
