#!/usr/bin/env python3
# from typing import *

# def solve(N: int, t: List[int], x: List[int], y: List[int]) -> str:
def solve(N, t, x, y):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N = int(input())
    t = [None for _ in range(N)]
    x = [None for _ in range(N)]
    y = [None for _ in range(N)]
    for i in range(N):
        t[i], x[i], y[i] = map(int, input().split())
    nch = solve(N, t, x, y)
    print(nch)

if __name__ == '__main__':
    main()
