#!/usr/bin/env python3
# from typing import *

# def solve(S: str, K: int) -> int:
def solve(S, K):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    S = next(tokens)
    K = int(next(tokens))
    assert next(tokens, None) is None
    gnf = solve(S, K)
    print(gnf)

if __name__ == '__main__':
    main()
