#!/usr/bin/env python3
# from typing import *

# def solve(N: int, M: int, K: int) -> int:
def solve(N, M, K):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N, M, K = map(int, input().split())
    xju = solve(N, M, K)
    print(xju)

if __name__ == '__main__':
    main()
