#!/usr/bin/env python3
# from typing import *

# def solve(A: int, B: float) -> int:
def solve(A, B):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    A = int(next(tokens))
    B = float(next(tokens))
    assert next(tokens, None) is None
    rao = solve(A, B)
    print(rao)

if __name__ == '__main__':
    main()
