#!/usr/bin/env python3
# from typing import *

# def solve(N: str) -> int:
def solve(N):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N = input()
    flz = solve(N)
    print(flz)

if __name__ == '__main__':
    main()
