#!/usr/bin/env python3
# from typing import *

# def solve(X: int, K: int, D: int) -> int:
def solve(X, K, D):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    X, K, D = map(int, input().split())
    dnd = solve(X, K, D)
    print(dnd)

if __name__ == '__main__':
    main()
