#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.6.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N = None  # TODO: edit here
    K = None  # TODO: edit here
    print(N)
    print(K)

if __name__ == "__main__":
    main()
