#!/usr/bin/env python3
# from typing import *



# def solve(N: str, K: str) -> int:
def solve(N, K):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.6.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N = input()
    K = input()
    a = solve(N, K)
    print(a)

if __name__ == '__main__':
    main()
