#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    H = random.randint(1, 10 ** 9)  # TODO: edit here
    W = random.randint(1, 10 ** 9)  # TODO: edit here
    M = random.randint(1, 10 ** 9)  # TODO: edit here
    h = [None for _ in range(M)]
    w = [None for _ in range(M)]
    for i in range(M):
        h[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        w[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(H, W, M)
    for i in range(M):
        print(h[i], w[i])

if __name__ == "__main__":
    main()
