#!/usr/bin/env python3
# from typing import *

# def solve(N: int, K: int) -> int:
def solve(N, K):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N, K = map(int, input().split())
    oes = solve(N, K)
    print(oes)

if __name__ == '__main__':
    main()
