#!/usr/bin/env python3
# from typing import *

# def solve(N: int, u: List[int], v: List[int]) -> int:
def solve(N, u, v):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N = int(input())
    u = [None for _ in range(N - 1)]
    v = [None for _ in range(N - 1)]
    for i in range(N - 1):
        u[i], v[i] = map(int, input().split())
    gwi = solve(N, u, v)
    print(gwi)

if __name__ == '__main__':
    main()
