#!/usr/bin/env python3
# from typing import *

# def solve(L: int, R: int, d: int) -> int:
def solve(L, R, d):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    L, R, d = map(int, input().split())
    ryg = solve(L, R, d)
    print(ryg)

if __name__ == '__main__':
    main()
