#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N = random.randint(1, 10 ** 9)  # TODO: edit here
    Q = random.randint(1, 10 ** 9)  # TODO: edit here
    P = [None for _ in range(Q)]
    A = [None for _ in range(Q)]
    B = [None for _ in range(Q)]
    for i in range(Q):
        P[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        A[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        B[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(N, Q)
    for i in range(Q):
        print(P[i], A[i], B[i])

if __name__ == "__main__":
    main()
