#!/usr/bin/env python3
# from typing import *

# def solve(N: int, Q: int, P: List[int], A: List[int], B: List[int]) -> Any:
def solve(N, Q, P, A, B):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N, Q = map(int, input().split())
    P = [None for _ in range(Q)]
    A = [None for _ in range(Q)]
    B = [None for _ in range(Q)]
    for i in range(Q):
        P[i], A[i], B[i] = map(int, input().split())
    ans = solve(N, Q, P, A, B)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
