#!/usr/bin/env python3
# from typing import *

# def solve(N: int, D: int, X: List[int], Y: List[int]) -> int:
def solve(N, D, X, Y):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N, D = map(int, input().split())
    X = [None for _ in range(N)]
    Y = [None for _ in range(N)]
    for i in range(N):
        X[i], Y[i] = map(int, input().split())
    zsu = solve(N, D, X, Y)
    print(zsu)

if __name__ == '__main__':
    main()
