#!/usr/bin/env python3
# from typing import *

# def solve(N: int, K: int, P: List[int], C: List[int]) -> int:
def solve(N, K, P, C):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    K = int(next(tokens))
    P = [None for _ in range(N)]
    C = [None for _ in range(N)]
    for i in range(N):
        P[i] = int(next(tokens))
    for i in range(N):
        C[i] = int(next(tokens))
    assert next(tokens, None) is None
    pop = solve(N, K, P, C)
    print(pop)

if __name__ == '__main__':
    main()
