#!/usr/bin/env python3
# from typing import *

# def solve(X: int, Y: int) -> str:
def solve(X, Y):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    X, Y = map(int, input().split())
    xcy = solve(X, Y)
    print(xcy)

if __name__ == '__main__':
    main()
