#!/usr/bin/env python3
# from typing import *

# def solve(X: int, A: int, B: int) -> int:
def solve(X, A, B):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    X = int(input())
    A = int(input())
    B = int(input())
    hfo = solve(X, A, B)
    print(hfo)

if __name__ == '__main__':
    main()
