#!/usr/bin/env python3
# from typing import *

# def solve(N: str, S: str, Q: str, Query: List[str]) -> Any:
def solve(N, S, Q, Query):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N = input()
    S = input()
    Q = input()
    Query = [None for _ in range(Q)]
    for i in range(Q):
        Query[i] = input()
    ans = solve(N, S, Q, Query)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
