#!/usr/bin/env python3
# from typing import *



# def solve(S: str) -> str:
def solve(S):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.6.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    S = input()
    a = solve(S)
    print(a)

if __name__ == '__main__':
    main()
