#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    R = random.randint(1, 10 ** 9)  # TODO: edit here
    C = random.randint(1, 10 ** 9)  # TODO: edit here
    K = random.randint(1, 10 ** 9)  # TODO: edit here
    r = [None for _ in range(K)]
    c = [None for _ in range(K)]
    v = [None for _ in range(K)]
    for i in range(K):
        r[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        c[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        v[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(R, C, K)
    for i in range(K):
        print(r[i], c[i], v[i])

if __name__ == "__main__":
    main()
