#!/usr/bin/env python3
# from typing import *

# def solve(R: int, C: int, K: int, r: List[int], c: List[int], v: List[int]) -> int:
def solve(R, C, K, r, c, v):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    R, C, K = map(int, input().split())
    r = [None for _ in range(K)]
    c = [None for _ in range(K)]
    v = [None for _ in range(K)]
    for i in range(K):
        r[i], c[i], v[i] = map(int, input().split())
    kdp = solve(R, C, K, r, c, v)
    print(kdp)

if __name__ == '__main__':
    main()
