#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N = random.randint(1, 10 ** 9)  # TODO: edit here
    X = random.randint(1, 10 ** 9)  # TODO: edit here
    T = random.randint(1, 10 ** 9)  # TODO: edit here
    print(N, X, T)

if __name__ == "__main__":
    main()
