#!/usr/bin/env python3
# from typing import *

# def solve(N: int, X: int, T: int) -> int:
def solve(N, X, T):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N, X, T = map(int, input().split())
    zre = solve(N, X, T)
    print(zre)

if __name__ == '__main__':
    main()
