#!/usr/bin/env python3
# from typing import *

# def solve(x: int, a: int, b: int) -> Any:
def solve(x, a, b):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    x, a, b = map(int, input().split())
    ans = solve(x, a, b)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
