#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N = random.randint(1, 10 ** 9)  # TODO: edit here
    p = [None for _ in range(N - 1)]
    for i in range(N - 1):
        p[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(N)
    print(*[p[i] for i in range(N - 1)])

if __name__ == "__main__":
    main()
