#!/usr/bin/env python3
# from typing import *

# def solve(N: str, p: List[str]) -> str:
def solve(N, p):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = next(tokens)
    p = [None for _ in range(N - 1)]
    for i in range(N - 1):
        p[i] = next(tokens)
    assert next(tokens, None) is None
    T = solve(N, p)
    print(T)

if __name__ == '__main__':
    main()
