#!/usr/bin/env python3
# from typing import *

# def solve(N: int, A: int, op: List[str], B: List[int]) -> Any:
def solve(N, A, op, B):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    op = [None for _ in range(N)]
    B = [None for _ in range(N)]
    A = int(next(tokens))
    for i in range(N):
        op[i] = next(tokens)
        B[i] = int(next(tokens))
    assert next(tokens, None) is None
    ans = solve(N, A, op, B)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
