#!/usr/bin/env python3
# from typing import *

# def solve(S: str, Q: str, Query: List[str]) -> str:
def solve(S, Q, Query):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    S = input()
    Q = input()
    Query = [None for _ in range(Q)]
    for i in range(Q):
        Query[i] = input()
    cec = solve(S, Q, Query)
    print(cec)

if __name__ == '__main__':
    main()
