#!/usr/bin/env python3
# from typing import *

# def solve(n: int, a: int, b: int) -> int:
def solve(n, a, b):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    n, a, b = map(int, input().split())
    bib = solve(n, a, b)
    print(bib)

if __name__ == '__main__':
    main()
