#!/usr/bin/env python3
# from typing import *

# def solve(A: int, B: int) -> int:
def solve(A, B):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    A, B = map(int, input().split())
    ejj = solve(A, B)
    print(ejj)

if __name__ == '__main__':
    main()
