#!/usr/bin/env python3
# from typing import *

# def solve(N: str, c: List[str]) -> int:
def solve(N, c):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = next(tokens)
    c = [None for _ in range(N)]
    for i in range(N):
        c[i] = next(tokens)
    assert next(tokens, None) is None
    ijw = solve(N, c)
    print(ijw)

if __name__ == '__main__':
    main()
