#!/usr/bin/env python3
# from typing import *

# def solve(W: int, H: int, K: int) -> int:
def solve(W, H, K):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    W, H, K = map(int, input().split())
    ojs = solve(W, H, K)
    print(ojs)

if __name__ == '__main__':
    main()
