#!/usr/bin/env python3
# from typing import *

# def solve(N: int, S: str) -> str:
def solve(N, S):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N = int(input())
    S = input()
    bpk = solve(N, S)
    print(bpk)

if __name__ == '__main__':
    main()
