#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.6.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    S = ''.join([random.choice('abcde') for range(random.randint(1, 100))])  # TODO: edit here
    T = ''.join([random.choice('abcde') for range(random.randint(1, 100))])  # TODO: edit here
    print(S)
    print(T)

if __name__ == "__main__":
    main()
