#!/usr/bin/env python3
# from typing import *

# def solve(a: int, b: int) -> str:
def solve(a, b):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    a, b = map(int, input().split())
    xct = solve(a, b)
    print(xct)

if __name__ == '__main__':
    main()
