#!/usr/bin/env python3
# from typing import *

# def solve(a: int) -> int:
def solve(a):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    a = int(input())
    mkh = solve(a)
    print(mkh)

if __name__ == '__main__':
    main()
