#!/usr/bin/env python3
# from typing import *

# def solve(n: int, k: int) -> int:
def solve(n, k):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    n, k = map(int, input().split())
    nif = solve(n, k)
    print(nif)

if __name__ == '__main__':
    main()
