#!/usr/bin/env python3
# from typing import *

# def solve(iux: int, vwy: List[int]) -> Any:
def solve(iux, vwy):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    iux = int(input())
    vwy = [None for _ in range(iux)]
    for i in range(iux):
        vwy[i] = int(input())
    ans = solve(iux, vwy)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
