#!/usr/bin/env python3
# from typing import *

# def solve(K: int, S: str) -> str:
def solve(K, S):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    K = int(input())
    S = input()
    gbo = solve(K, S)
    print(gbo)

if __name__ == '__main__':
    main()
