#!/usr/bin/env python3
# from typing import *

# def solve(A: int, op: str, B: int) -> str:
def solve(A, op, B):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    A = int(next(tokens))
    op = next(tokens)
    B = int(next(tokens))
    assert next(tokens, None) is None
    kic = solve(A, op, B)
    print(kic)

if __name__ == '__main__':
    main()
