#!/usr/bin/env python3
# from typing import *

# def solve(K: int) -> int:
def solve(K):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    K = int(input())
    mbn = solve(K)
    print(mbn)

if __name__ == '__main__':
    main()
