#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N = random.randint(1, 10 ** 9)  # TODO: edit here
    A = [None for _ in range(N)]
    B = [None for _ in range(N)]
    C = [None for _ in range(N)]
    M = random.randint(1, 10 ** 9)  # TODO: edit here
    D = [None for _ in range(M)]
    E = [None for _ in range(M)]
    F = [None for _ in range(M)]
    for i in range(N):
        A[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        B[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        C[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    for i in range(M):
        D[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        E[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        F[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(N, M)
    for i in range(N):
        print(A[i], B[i], C[i])
    for i in range(M):
        print(D[i], E[i], F[i])

if __name__ == "__main__":
    main()
