#!/usr/bin/env python3
# from typing import *

# def solve(gew: int, mji: List[int]) -> Any:
def solve(gew, mji):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    gew = int(input())
    mji = [None for _ in range(gew)]
    for i in range(gew):
        mji[i] = int(input())
    ans = solve(gew, mji)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
