#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.6.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N = None  # TODO: edit here
    Q = None  # TODO: edit here
    Query = [None for _ in range(Q)]
    for i in range(Q):
        Query[i] = None  # TODO: edit here
    print(N, Q)
    for i in range(Q):
        print(Query[i])

if __name__ == "__main__":
    main()
