#!/usr/bin/env python3
# from typing import *

# def solve(N: int, K: int, p: List[int]) -> int:
def solve(N, K, p):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = int(next(tokens))
    K = int(next(tokens))
    p = [None for _ in range(N)]
    for i in range(N):
        p[i] = int(next(tokens))
    assert next(tokens, None) is None
    rqt = solve(N, K, p)
    print(rqt)

if __name__ == '__main__':
    main()
