#!/usr/bin/env python3
# from typing import *

# def solve(N: int, K: int, P: int) -> int:
def solve(N, K, P):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N, K, P = map(int, input().split())
    njx = solve(N, K, P)
    print(njx)

if __name__ == '__main__':
    main()
