#!/usr/bin/env python3
# from typing import *

# def solve(A: int, B: int, C: int, K: int) -> int:
def solve(A, B, C, K):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    A, B, C, K = map(int, input().split())
    iii = solve(A, B, C, K)
    print(iii)

if __name__ == '__main__':
    main()
