#!/usr/bin/env python3
# from typing import *

# def solve(S: str, T: str) -> str:
def solve(S, T):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    S = input()
    T = input()
    ucb = solve(S, T)
    print(ucb)

if __name__ == '__main__':
    main()
