#!/usr/bin/env python3
# from typing import *



# def solve(S: str, T: str, A: int, B: int, U: str) -> Any:
def solve(S, T, A, B, U):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.6.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    S, T = input().split()
    A, B = map(int, input().split())
    U = input()
    ans = solve(S, T, A, B, U)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
