#!/usr/bin/env python3
# from typing import *

# def solve(N: int, R: int) -> int:
def solve(N, R):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N, R = map(int, input().split())
    sdo = solve(N, R)
    print(sdo)

if __name__ == '__main__':
    main()
