#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.6.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N = random.randint(1, 10 ** 9)  # TODO: edit here
    K = random.randint(1, 1000)  # TODO: edit here
    L = [None for _ in range(K)]
    R = [None for _ in range(K)]
    for i in range(K):
        L[i] = random.randint(1, 10 ** 9)  # TODO: edit here
        R[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(N, K)
    for i in range(K):
        print(L[i], R[i])

if __name__ == "__main__":
    main()
