#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N = random.randint(1, 10 ** 9)  # TODO: edit here
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    M = random.randint(1, 10 ** 9)  # TODO: edit here
    B = [None for _ in range(M)]
    for i in range(M):
        B[i] = random.randint(1, 10 ** 9)  # TODO: edit here
    command = random.randint(1, 10 ** 9)  # TODO: edit here
    print(N)
    print(*[A[i] for i in range(N)])
    print(M)
    print(*[B[i] for i in range(M)])
    print(command)

if __name__ == "__main__":
    main()
