#!/usr/bin/env python3
# from typing import *

# def solve(N: str, A: List[str], M: str, B: List[str], command: str) -> Any:
def solve(N, A, M, B, command):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = next(tokens)
    A = [None for _ in range(N)]
    for i in range(N):
        A[i] = next(tokens)
    M = next(tokens)
    B = [None for _ in range(M)]
    for i in range(M):
        B[i] = next(tokens)
    command = next(tokens)
    assert next(tokens, None) is None
    ans = solve(N, A, M, B, command)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
