#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    # failed to analyze input format
    n = random.randint(1, 10 ** 9)  # TODO: edit here
    a = [random.randint(1, 10 ** 9) for _ in range(n)]  # TODO: edit here
    print(n)  # TODO: edit here
    print(*a)  # TODO: edit here

if __name__ == "__main__":
    main()
