#!/usr/bin/env python3
# from typing import *

# def solve(n: int, a: List[int]) -> float:
def solve(n, a):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    # failed to analyze input format
    n = int(input())  # TODO: edit here
    a = list(map(int, input().split()))  # TODO: edit here
    kjt = solve(n, a)
    print(kjt)

if __name__ == '__main__':
    main()
