#!/usr/bin/env python3
# from typing import *

# def solve(S: str) -> int:
def solve(S):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    S = input()
    smx = solve(S)
    print(smx)

if __name__ == '__main__':
    main()
