#!/usr/bin/env python3
# from typing import *

# def solve(A: int, B: int, C: int, X: int) -> int:
def solve(A, B, C, X):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    A = int(input())
    B = int(input())
    C = int(input())
    X = int(input())
    anc = solve(A, B, C, X)
    print(anc)

if __name__ == '__main__':
    main()
