#!/usr/bin/env python3
# from typing import *

# def solve(N: int, K: int, x: List[int], y: List[int], c: List[int]) -> float:
def solve(N, K, x, y, c):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N, K = map(int, input().split())
    x = [None for _ in range(N)]
    y = [None for _ in range(N)]
    c = [None for _ in range(N)]
    for i in range(N):
        x[i], y[i], c[i] = map(int, input().split())
    dpd = solve(N, K, x, y, c)
    print(dpd)

if __name__ == '__main__':
    main()
