#!/usr/bin/env python3
# from typing import *

# def solve(N: int) -> Any:
def solve(N):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N = int(input())
    ans = solve(N)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
