#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
import random

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N = random.randint(1, 10 ** 9)  # TODO: edit here
    A = [[None for _ in range(2*N + 3)] for _ in range(2*N + 3)]
    for j in range(N + 4):
        for i in range(N - 1):
            A[i + j][i + j] = random.randint(1, 10 ** 9)  # TODO: edit here
    print(N)
    for j in range(N + 4):
        print(*[A[i + j][i + j] for i in range(N - 1)])

if __name__ == "__main__":
    main()
