#!/usr/bin/env python3
# from typing import *

# def solve(N: str, A: List[List[str]]) -> int:
def solve(N, A):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    import sys
    tokens = iter(sys.stdin.read().split())
    N = next(tokens)
    A = [[None for _ in range(2*N + 3)] for _ in range(2*N + 3)]
    for j in range(N + 4):
        for i in range(N - 1):
            A[i + j][i + j] = next(tokens)
    assert next(tokens, None) is None
    ncw = solve(N, A)
    print(ncw)

if __name__ == '__main__':
    main()
