#!/usr/bin/env python3
# from typing import *

# def solve(N: int, Q: int, A: List[int], B: List[int], C: List[int], D: List[int]) -> Any:
def solve(N, Q, A, B, C, D):
    pass  # TODO: edit here

# generated by online-judge-template-generator v4.1.0 (https://github.com/kmyk/online-judge-template-generator)
def main():
    N, Q = map(int, input().split())
    A = [None for _ in range(N)]
    B = [None for _ in range(N)]
    C = [None for _ in range(Q)]
    D = [None for _ in range(Q)]
    for i in range(N):
        A[i], B[i] = map(int, input().split())
    for i in range(Q):
        C[i], D[i] = map(int, input().split())
    ans = solve(N, Q, A, B, C, D)
    print(ans)  # TODO: edit here

if __name__ == '__main__':
    main()
